name: release

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:ci

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Create release pull request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
